# Generated by Django 5.0.6 on 2024-07-06 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverecord',
            name='days',
        ),
    ]
